[tool.poetry]
name = "gptme-rag"
version = "0.1.0"
description = "RAG implementation for gptme context management"
authors = ["Bob <bob@gptme.org>"]

[tool.poetry.dependencies]
python = "^3.10"
chromadb = "^0.4.22"
sentence-transformers = "^2.2.2"
pydantic = "^2.5.2"
click = "^8.1.7"
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.11.0"
ruff = "^0.1.6"
mypy = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry-core.backend"
